definitions:
  models.VehicleByYear:
    properties:
      total:
        type: integer
      year:
        type: integer
    type: object
  models.VehiclePopularity:
    properties:
      make:
        type: string
      model:
        type: string
      total:
        type: integer
    type: object
  web.ErrorResponse:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
paths:
  /byyear:
    get:
      consumes:
      - application/json
      description: Fetches a list of vehicles filtered as per the query parameter.
      parameters:
      - description: Filter (all, hybrid, or electric)
        in: query
        name: filter
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: A list of vehicles sorted by year
          schema:
            items:
              $ref: '#/definitions/models.VehicleByYear'
            type: array
        "400":
          description: 'Invalid filter - The filter query parameter is required and
            must be one of ''all'', ''hybrid'', or ''electric''. Response body will
            contain: {''error'': ''Invalid filter''}'
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "404":
          description: Method not supported
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get vehicles by year
      tags:
      - vehicles
  /popular:
    get:
      consumes:
      - application/json
      description: Fetches a list of popular vehicles, sorted and filtered as per
        query parameters.
      parameters:
      - description: Sort order (asc or desc)
        in: query
        name: sort
        type: string
      - description: Filter (all, hybrid, or electric)
        in: query
        name: filter
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: A list of vehicles
          schema:
            items:
              $ref: '#/definitions/models.VehiclePopularity'
            type: array
        "400":
          description: Invalid sort order or filter
          schema:
            type: string
        "404":
          description: Method not supported
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get popular vehicles
      tags:
      - vehicles
swagger: "2.0"
